export const EVENT_SHOOT_REQUESTED = 'EVENT_SHOOT_REQUESTED';
export const EVENT_SHOT = 'EVENT_SHOT';

export const CONST_CELL_INIT = 'CONST_CELL_INIT';
export const CONST_CELL_MISSED = 'CONST_CELL_MISSED';
